flask_compass/__init__.py
from flask import Flask 

from .commands import create_tables
from .UsuarioModel import User
from .ItemModel import Item
from .extensions import db, login_manager
from flask_compass.routes.main import main
from flask_compass.routes.LoginController import LoginController
from flask_compass.routes.AcessoController import AcessoController
from flask_compass.routes.ItemController import ItemController

def create_app(config_file='settings.py'):
    app = Flask(__name__)
    app.secret_key = 'oisadjva9sd8uvasdvojasasdfasdfasdf'

    app.config.from_pyfile(config_file)

    db.init_app(app)

    login_manager.init_app(app)

    login_manager.login_view = 'auth.login'

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(user_id)

    app.register_blueprint(LoginController)
    app.register_blueprint(AcessoController)
    app.register_blueprint(ItemController)
    app.register_blueprint(main)

    app.cli.add_command(create_tables)

    return app

flask_compass/routes/AcessoController.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_compass.extensions import db
from flask_compass.UsuarioModel import User
from flask_login import login_user, logout_user
from werkzeug.security import check_password_hash

AcessoController = Blueprint('AcessoController', __name__)

@AcessoController.route('/profile', methods=['GET', 'POST'])
def criarUsuario():
    if request.method == 'POST':
        name = request.form['nome']
        username = request.form['username']
        cidade = request.form['cidade']
        estado = request.form['estado']
        password = request.form['password']

        user = User(
            name=name, 
            username=username,
            cidade=cidade,  
            estado=estado,
            unhashed_password=password
        )

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('LoginController.fazerLogin'))

    return render_template('AcessoView.html')

flask_compass/routes/ItemController.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_compass.extensions import db
from flask_compass.ItemModel import Item
from flask_login import login_user, logout_user
from werkzeug.security import check_password_hash

ItemController = Blueprint('ItemController', __name__)

@ItemController.route('/cadastraItem', methods=['GET', 'POST'])
def addItem():
    if request.method == 'POST':
        tipo = request.form['tipo']
        titulo = request.form['titulo']
        diretor = request.form['diretor']
        pais = request.form['pais']
        ano = request.form['ano']
        genero = request.form['genero']

        item = Item(
            tipo=tipo, 
            titulo=titulo,
            diretor=diretor,  
            pais=pais,
            ano=ano,
            genero=genero
        )

        db.session.add(item)
        db.session.commit()

        return redirect(url_for('main.home'))

    return render_template('ItemView.html')

flask_compass/routes/LoginController.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_compass.extensions import db
from flask_compass.UsuarioModel import User
from flask_login import login_user, logout_user
from werkzeug.security import check_password_hash

LoginController = Blueprint('LoginController', __name__)

@LoginController.route('/', methods=['GET', 'POST'])
def fazerLogin():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']

        user = User.query.filter_by(username=username).first()

        error_message = ''

        if not user or not check_password_hash(user.password, password):
            error_message = 'Senha errada'

        if not error_message:
            login_user(user)
            return redirect(url_for('main.home'))

    return render_template('LoginView.html')

flask_compass/routes/main.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import current_user, login_required
from flask_compass.extensions import db
from flask_compass.UsuarioModel import User

main = Blueprint('main', __name__)

@main.route('/home')
def home():
    return render_template('AvaliaView.html')

@main.route('/cadastro')
def cadastro():
    return render_template('ItemView.html')

flask_compass/templates/AcessoView.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Login</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>

<body>
  <section class="hero is-fullheight">
    <div class="hero-body">
      <div class="container">
        <img src="{{url_for('static', filename='compass_logo_new.png')}}" class="is-centered"/>
        <div class="columns is-centered">
          <div class="column is-half">
            <form method="POST" method="POST" action="{{ url_for('AcessoController.criarUsuario') }}">
              <div class="field">
                <label class="label">Nome</label>
                <p class="control has-icons-left">
                  <input class="input" type="nome" name="nome" placeholder="Nome">
                  <span class="icon is-small is-left">
                    <i class="fas fa-user"></i>
                  </span>
                </p>
              </div>
              <div class="field">
                <label class="label">Username</label>
                <div class="control has-icons-left has-icons-right">
                  <input class="input" type="text" name="username" placeholder="Username">
                  <span class="icon is-small is-left">
                    <i class="fas fa-user"></i>
                  </span>
                </div>
              </div>
              <div class="field">
                <label class="label">Cidade</label>
                <p class="control has-icons-left">
                  <input class="input" type="cidade" name="cidade" placeholder="Cidade">
                  <span class="icon is-small is-left">
                    <i class="fas fa-city"></i>
                  </span>
                </p>
              </div>
              <div class="field">
                <label class="label">Estado</label>
                <p class="control has-icons-left">
                  <input class="input" type="estado" name="estado" placeholder="Estado">
                  <span class="icon is-small is-left">
                    <i class="fas fa-flag"></i>
                  </span>
                </p>
              </div>
              <div class="field">
                <label class="label">Password</label>
                <p class="control has-icons-left">
                  <input class="input" type="password" name="password" placeholder="Password">
                  <span class="icon is-small is-left">
                    <i class="fas fa-lock"></i>
                  </span>
                </p>
              </div>
              <div class="field">
                <p class="control">
                  <button type="submit" class="button is-success is-centered" >
                    Submit
                  </button>
                </p>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
</body>

</html>

flask_compass/templates/AvaliaView.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Login</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>
<body>
  <section class="section">
    <div class="columns is-4 is-multiline is-mobile">
        <div class="column is-half">
            <figure class="image is-1280x1280">
                <img src="{{url_for('static', filename='compass_logo_new.png')}}" class="is-centered"/>
            </figure>
        </div>
      <div class="column is-gapless">
      <div class="field">
          <label class="label"></label>
          <div class="control">
            <input class="input" type="text" placeholder="Buscar livros/filmes/séries">
          </div>
      </div>
      </div>
      <div class="column is-gapless">
        <div class="field is-grouped"></div>
          <div class="control">
            <button class="button is-link is-success is-sentered">Buscar</button>
            

          </div>
      </div>
      <div class="box has-background-light">
      <div class="column is-gapless">
        <div class="control">
          <button class="button is-link is-success is-sentered">
            <a href="{{ url_for('ItemController.addItem')}}">Adicionar Item</a>
          </button>
        </div>
      </div>
      </div>
    </div>
  </section>
  <section class="section">
    <div class="box has-background-light">
    <div class="columns is-3 is-multiline is-mobile">
    <div class="column is-half">
        <div class="box">
            <article class="media">
              <div class="media-left">
                <figure class="image is-64x64">
                  <img src="https://bulma.io/images/placeholders/128x128.png" alt="Image">
                </figure>
              </div>
              <div class="media-content">
                <div class="content">
                  <p>
                    <strong>Lucas</strong> <small>@Lucas</small> <small>31m</small>
                    <br>
                    Sugestão de Amizade
                    <p>Itens Relacionados: Generos Politicos, Drama, Ação e Aventura:. "A Politica da Prudencia; O Ultimato Bournie; O Atirador"</p>

                  </p>
              </div>
            </article>
        </div>
        <div class="box">
            <article class="media">
              <div class="media-left">
                <figure class="image is-64x64">
                  <img src="https://bulma.io/images/placeholders/128x128.png" alt="Image">
                </figure>
              </div>
              <div class="media-content">
                <div class="content">
                  <p>
                    <strong>Dyol</strong> <small>@Dyol</small> <small>31m</small>
                    <br>
                    Sugestão de Amizade
                    <p>Itens Relacionados: Generos Adulto, Comédia, Ficção:. "Bruna Surfistinha; Gente Grande; Harry Potter"</p>
                  </p>
              </div>
            </article>
        </div>
        <div class="box">
            <article class="media">
              <div class="media-left">
                <figure class="image is-64x64">
                  <img src="https://bulma.io/images/placeholders/128x128.png" alt="Image">
                </figure>
              </div>
              <div class="media-content">
                <div class="content">
                  <p>
                    <strong>Augusto Rosasco</strong> <small>@augusto</small> <small>31m</small>
                    <br>
                    Sugestão de Amizade
                    <p>Itens Relacionados: Generos Economicos, Terror, Romance:. "A Riqueza das Nações; O Exorcismo de Emily Rose; Para Todos os Garotos que Ja Amei"</p>
                  </p>
              </div>
            </article>
        </div>
    </div>
    <div class="column is-half">
      <div class="box">
        <label class="label">"Era Uma Vez em... Hollywood"</label>
        <p>@Victor:. "Melhor Filme de Todos.... Meus Deus!!!" Nota: 10</p>
        <p>@Talita:. "Adoro o Leo!" Nota: 10</p>
        <p>@KarinaWaggen:. "O Roteiro inspira. Um verdadeiro Classico" Nota: 9</p>
        <p>@DonaldTrump:. "Amazing, like everything made by America" Nota: 10</p>
      </div>
        </p>
    <form method="POST" method="POST"></form>
        <div class="control">
            <button class="button is-link is-light">Like</button>
        </div>
        <div class="field">
            <label class="label">Nota</label>
             <div class="control has-icons-left">
                 <div class="select is-fullwidth">
                 <select name="tipo">
                     <option>0</option>
                     <option>1</option>
                     <option>2</option>
                     <option>3</option>
                     <option>4</option>
                     <option>5</option>
                     <option>6</option>
                     <option>7</option>
                     <option>8</option>
                     <option>9</option>
                     <option>10</option>
                 </select>
                 </div>
                 <span class="icon is-small is-left">
                    <i class="fas fa-user"></i>
                 </span>
             </div>
        </div>
        <div class="field">
            <label class="label">Comentário</label>
            <div class="control">
                <textarea class="textarea" placeholder="Faça um novo Comentário"></textarea>
            </div>
            </div> 
            <div class="field">
                <p class="control">
                  <button type="submit" class="button is-success is-centered" >
                    Submit
                  </button>
                </p>
            </div> 
        </div> 
    </form>
  </box>
  </section>
</body>
</html>

flask_compass/templates/ItemView.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Login</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>

<body>
  <section class="hero is-fullheight">
    <div class="hero-body">
      <div class="container">
        <img src="{{url_for('static', filename='compass_logo_new.png')}}" class="is-centered"/>
        <div class="columns is-centered">
          <div class="column is-half">
            <form method="POST" method="POST" action="{{ url_for('ItemController.addItem') }}">
              <div class="field">
                   <label class="label">Tipo do Conteúdo</label>
                    <div class="control has-icons-left">
                        <div class="select is-fullwidth">
                        <select name="tipo">
                            <option>Filme</option>
                            <option>Serie</option>
                            <option>livro</option>
                        </select>
                        </div>
                        <span class="icon is-small is-left">
                           <i class="fas fa-user"></i>
                        </span>
                    </div>
               </div>
              <div class="field">
                <label class="label">Título</label>
                <p class="control has-icons-left">
                  <input class="input" type="titulo" name="titulo" placeholder="Os Trombadinhas">
                  <span class="icon is-small is-left">
                    <i class="fas fa-user"></i>
                  </span>
                </p>
              </div>
              <div class="field">
                <label class="label">Diretor/Autor</label>
                <div class="control has-icons-left has-icons-right">
                  <input class="input" type="diretor" name="diretor" placeholder="Anselmo Duarte">
                  <span class="icon is-small is-left">
                    <i class="fas fa-user"></i>
                  </span>
                </div>
              </div>
              <div class="field">
                <label class="label">País de origem</label>
                <p class="control has-icons-left">
                  <input class="input" type="pais" name="pais" placeholder="Brasil">
                  <span class="icon is-small is-left">
                    <i class="fas fa-flag"></i>
                  </span>
                </p>
              </div>
              <div class="field">
                <label class="label">Ano de origem</label>
                <p class="control has-icons-left">
                  <input class="input" type="ano" name="ano" placeholder="1979">
                  <span class="icon is-small is-left">
                    <i class="fas fa-lock"></i>
                  </span>
                </p>
              </div>
              <div class="field">
                <label class="label">Genêro</label>
                <p class="control has-icons-left">
                  <input class="input" type="genero" name="genero" placeholder="Aventura">
                  <span class="icon is-small is-left">
                    <i class="fas fa-lock"></i>
                  </span>
                </p>
              </div>
              <div class="field">
                <p class="control">
                  <button type="submit" class="button is-success is-centered" >
                    Submit
                  </button>
                </p>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
</body>

</html>

flask_compass/templates/LoginView.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Login</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>

<body>
  <section class="hero is-fullheight">
    <div class="hero-body">
      <div class="container">
        <img src="{{url_for('static', filename='compass_logo_new.png')}}"/>
        <div class="columns is-centered">
          <div class="column is-half">
            <form method="POST" action="{{ url_for('LoginController.fazerLogin')}}">
              <div class="field">
                <label class="label">Username</label>
                <div class="control has-icons-left has-icons-right">
                  <input class="input" type="text" name="username" placeholder="Username">
                  <span class="icon is-small is-left">
                    <i class="fas fa-user"></i>
                  </span>
                </div>
              </div>
              <div class="field">
                <label class="label">Password</label>
                <p class="control has-icons-left">
                  <input class="input" type="password" name="password" placeholder="Password">
                  <span class="icon is-small is-left">
                    <i class="fas fa-lock"></i>
                  </span>
                </p>
              </div>
              <div class="field">
                <p class="control">
                  <button type="submit" class="button is-success">
                    Login
                  </button>
                </p>
              </div>
              <div class="field">
                <p class="control">
                  <button class="button is-success">
                    <a href="{{ url_for('AcessoController.criarUsuario')}}">Cadastre-se</a>
                  </button>
                </p>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
</body>

</html>